services:
  - type: web
    name: contextual-ai-orchestrator
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app1:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
